name: smn
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  diacritic: ^0.1.6

  firebase_core: 3.13.0
  firebase_messaging: 15.2.5

  flutter_local_notifications: 19.2.1

  flutter:
    sdk: flutter
  geocoding: 3.0.0
  geolocator: 13.0.2
  http: ^1.3.0
  intl: 0.20.2
  provider: 6.1.2
  shared_preferences: ^2.5.3
  weather_icons: ^3.0.0


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/data/datos_municipios.json"
    - "assets/data/pronosticos.json"
    - "assets/data/dia1.json"
    - "assets/data/dia2.json"
    - "assets/data/dia3.json"
    - "assets/data/dia4.json"
